export enum WokeValues {
    ANTI_FAMILY = "ANTI_FAMILY", 
    GENDER_IDEOLOGY = "GENDER_IDEOLOGY", 
    RACE_HUSTLER = "RACE_HUSTLER", 
    CHILDREN_SEXUALIZER = "CHILDREN_SEXUALIZER", 
    FEMINISM = "FEMINISM",  
    TERRORISM = "TERRORISM",
    HATE_GOD = "HATE_GOD", 
    HATE_COUNTRY = "HATE_COUNTRY"
  }
